apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        # Cleanup step
        rm -rf /workspace/source/*

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  steps:
    - name: nose-tests
      image: python:3.9-slim
      script: |
        # Install dependencies
        pip install nose coverage
        # Run the tests
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
